### ISSUE TITLE
Visual design: add some padding to areas of the sidebar

### ISSUE THREAD

**Issue by arrowtype** [Lorp/samsa#32]
Currently, many areas in the sidebar have no padding, which makes them slightly stressful to look at and use, especially if the window is full screen and these are right on the edge of my clickable area.

![no-padding](https://user-images.githubusercontent.com/45946693/80822503-dc98f600-8ba8-11ea-951d-b3c29474608b.png)

A very simple and effective improvement would be adding `padding: 0.5 rem` to the divs inside each panel:

![padding](https://user-images.githubusercontent.com/45946693/80822987-c17ab600-8ba9-11ea-82e1-281c2b9e4996.png)

This is actually achievable with just a couple lines of CSS:

```css
.panel>div {
    padding: 0.25rem 0.75rem;   /* 4px of space at top & bottom, 12px space on left & right */
    box-sizing: border-box; /* prevents width of div from exceed width of parent */
}
```
